"""Markdown report renderer (spec §4.5).

Two sections:
- **This week (limited-time free-to-keep)** — claim-window giveaways.
- **Permanent paid→free conversions** — no end date.

Plus a JSON dump `free_games.json` of the passing records for downstream use.
"""
from __future__ import annotations

import datetime as _dt
from typing import List

from .model import GameRecord


def _price(rec: GameRecord) -> str:
    cur = rec.original_price_currency or "USD"
    return f"{cur} {rec.original_price:,.2f}".replace(cur + " ", f"{cur} ")


def _short_date(iso: str | None) -> str:
    if not iso:
        return "—"
    try:
        d = _dt.datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return d.strftime("%Y-%m-%d")
    except (ValueError, TypeError):
        return "—"


def render_markdown(records: List[GameRecord], *, date: str | None = None,
                    source_feeds: List[str] | None = None) -> str:
    """Render the ranked record set to the primary markdown report."""
    date = date or _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d")
    limited = [r for r in records if not r.is_permanent]
    permanent = [r for r in records if r.is_permanent]

    lines = [
        f"# Free game alert — {date}",
        "",
        f"**{len(records)}** normally-paid games are now free.",
        "",
    ]

    if limited:
        lines += ["## This week (limited-time claims)", "",
                  "| Game | Store | Was | Free until | Claim |",
                  "|---|---|---|---|---|"]
        for r in limited:
            store = r.store.capitalize()
            lines.append(
                f"| {r.title} | {store} | {_price(r)} | {_short_date(r.end_date)} | "
                f"[link]({r.offer_url or r.store_url or '#'}) |"
            )
        lines.append("")

    if permanent:
        lines += ["## Permanent paid→free conversions", "",
                  "| Game | Store | Was | Free since | Link |",
                  "|---|---|---|---|---|"]
        for r in permanent:
            store = r.store.capitalize()
            lines.append(
                f"| {r.title} | {store} | {_price(r)} | {_short_date(r.free_since)} | "
                f"[link]({r.offer_url or r.store_url or '#'}) |"
            )
        lines.append("")

    if not records:
        lines += ["_No matches this run._", ""]

    feeds = ", ".join(sorted(set(source_feeds or []))) or "unknown"
    lines += [f"_Generated by free_games_tracker. Sources: {feeds}._", ""]
    return "\n".join(lines)


def render_json(records: List[GameRecord]) -> str:
    import json
    return json.dumps([r.to_dict() for r in records], indent=2, default=str)
